WIP

diff --git a/aws-sns-scheduler-service b/aws-sns-scheduler-service
--- a/aws-sns-scheduler-service
+++ b/aws-sns-scheduler-service
@@ -1,67 +1,84 @@
-#!/bin/bash
-# aws-sns-scheduler daemon
-# chkconfig: 345 20 80
-# description: aws-sns-scheduler daemon
-# processname: aws-sns-scheduler
-
-. /etc/init.d/functions
-
-PATH="/home/scheduler/env/bin:$PATH"
-DAEMON_PATH="/home/scheduler/aws-sns-scheduler"
-DAEMON="python main.py"
-DAEMON_USER='scheduler'
-DAEMONOPTS=""
+#!/bin/sh
+### BEGIN INIT INFO
+# Provides:          aws-sns-scheduler
+# Required-Start:    $local_fs $network $named $time $syslog
+# Required-Stop:     $local_fs $network $named $time $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Description:       aws-sns-scheduler-service
+### END INIT INFO
 
 NAME="aws-sns-scheduler"
-DESC="aws-sns-scheduler daemon"
-PIDFILE=/var/run/$NAME.pid
-SCRIPTNAME=/etc/init.d/$NAME
+SCRIPT_PATH="/home/scheduler/aws-sns-scheduler"
+SCRIPT="/home/scheduler/env/bin/python main.py"
+RUNAS=scheduler
+
+PIDFILE="/var/run/$NAME.pid"
+LOGFILE="/var/log/$NAME.log"
+
+start() {
+    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
+        echo 'Service already running' >&2
+        return 1
+    fi
+    echo 'Starting service…' >&2
+    touch $LOGFILE
+    chown $RUNAS:$RUNAS $LOGFILE
+    chmod 777 $LOGFILE
+    local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+    runuser -l $RUNAS -c "cd $SCRIPT_PATH; $CMD" > $PIDFILE
+    echo 'Service started' >&2
+}
+
+stop() {
+    if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+        echo 'Service not running' >&2
+        return 1
+    fi
+    echo 'Stopping service…' >&2
+    kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+    echo 'Service stopped' >&2
+}
+
+status() {
+    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
+        echo 'Service running' >&2
+        return 0
+    fi
+    echo 'Service not running' >&2
+    return 1
+}
+
+uninstall() {
+    echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+    local SURE
+    read SURE
+    if [ "$SURE" = "yes" ]; then
+        stop
+        rm -f "$PIDFILE"
+        echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+        update-rc.d -f <NAME> remove
+        rm -fv "$0"
+    fi
+}
 
 case "$1" in
-start)
-    printf "%-50s" "Starting $NAME..."
-    cd $DAEMON_PATH
-    PID=`daemon --user=$DAEMON_USER $DAEMON $DAEMONOPTS > /dev/null 2>&1 & echo $!`
-    #echo "Saving PID" $PID " to " $PIDFILE
-        if [ -z $PID ]; then
-            printf "%s\n" "Fail"
-        else
-            echo $PID > $PIDFILE
-            printf "%s\n" "Ok"
-        fi
-;;
-status)
-        printf "%-50s" "Checking $NAME..."
-        if [ -f $PIDFILE ]; then
-            PID=`cat $PIDFILE`
-            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-                printf "%s\n" "Process dead but pidfile exists"
-            else
-                echo "Running"
-            fi
-        else
-            printf "%s\n" "Service not running"
-        fi
-;;
-stop)
-        printf "%-50s" "Stopping $NAME"
-            PID=`cat $PIDFILE`
-            cd $DAEMON_PATH
-        if [ -f $PIDFILE ]; then
-            kill -HUP $PID
-            printf "%s\n" "Ok"
-            rm -f $PIDFILE
-        else
-            printf "%s\n" "pidfile not found"
-        fi
-;;
-
-restart)
-    $0 stop
-    $0 start
-;;
-
-*)
-        echo "Usage: $0 {status|start|stop|restart}"
-        exit 1
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    status)
+        status
+        ;;
+    uninstall)
+        uninstall
+        ;;
+    restart)
+        stop
+        start
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|restart|uninstall}"
 esac
